{"name":"verify restore contact text.....!!!","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Restore Contats] but found [Restore Contacts]","trace":"java.lang.AssertionError: expected [Restore Contats] but found [Restore Contacts]\r\n\tat org.testng.Assert.fail(Assert.java:97)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:136)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:575)\r\n\tat org.testng.Assert.assertEquals(Assert.java:585)\r\n\tat com.qa.contacts.tests.BackupRestoreTest.verifyRestoreContactsTextTest(BackupRestoreTest.java:35)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(Unknown Source)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:767)\r\n\tat org.testng.TestRunner.run(TestRunner.java:588)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1136)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1066)\r\n\tat org.testng.TestNG.run(TestNG.java:1034)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","description":"verify restore contact Text....","steps":[],"attachments":[{"name":"Page screenshot","source":"bec2a09b-581f-4520-9575-6f1b4f885420-attachment","type":"image/png"},{"name":"verifyRestoreContactsTextTest failed and screenshot taken!","source":"fcf7c4d7-771d-4fc7-aaca-a1b62e7d48fb-attachment","type":"text/plain"}],"parameters":[],"start":1593772855796,"stop":1593772857962,"uuid":"b50641e4-481e-494d-ba55-4f90324b42e8","historyId":"782ae47b4384132e193b7795780207a5","fullName":"com.qa.contacts.tests.BackupRestoreTest.verifyRestoreContactsTextTest","labels":[{"name":"package","value":"com.qa.contacts.tests.BackupRestoreTest"},{"name":"testClass","value":"com.qa.contacts.tests.BackupRestoreTest"},{"name":"testMethod","value":"verifyRestoreContactsTextTest"},{"name":"parentSuite","value":"POC Tests - Contacts Manager"},{"name":"suite","value":"BackupRestore Test"},{"name":"subSuite","value":"com.qa.contacts.tests.BackupRestoreTest"},{"name":"host","value":"VDLT247"},{"name":"thread","value":"10272@VDLT247.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"US - 607 : contacts backup restore page verify"},{"name":"epic","value":"Epic - 202 : Contacts Backup Restore Feature"},{"name":"severity","value":"normal"}],"links":[]}